# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ommunication_command.proto\x12\x10\x61utonomous_proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xce\x05\n\x14\x43ommunicationCommand\x12?\n\x07\x63ommand\x18\x01 \x01(\x0b\x32..autonomous_proto.CommunicationCommand.Command\x12\x41\n\x08response\x18\x02 \x01(\x0b\x32/.autonomous_proto.CommunicationCommand.Response\x1a\x98\x03\n\x07Markers\x12/\n\x0b\x65\x63u_send_on\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12/\n\x0b\x61uto_enable\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x0csteer_enable\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x0cspeed_enable\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12/\n\x0bgear_enable\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x33\n\x0fthrottle_enable\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x30\n\x0c\x62rake_enable\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12/\n\x0bpark_enable\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x1aJ\n\x07\x43ommand\x12?\n\x07markers\x18\x01 \x01(\x0b\x32..autonomous_proto.CommunicationCommand.Markers\x1aK\n\x08Response\x12?\n\x07markers\x18\x01 \x01(\x0b\x32..autonomous_proto.CommunicationCommand.Markersb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMUNICATIONCOMMAND._serialized_start=82
  _COMMUNICATIONCOMMAND._serialized_end=800
  _COMMUNICATIONCOMMAND_MARKERS._serialized_start=239
  _COMMUNICATIONCOMMAND_MARKERS._serialized_end=647
  _COMMUNICATIONCOMMAND_COMMAND._serialized_start=649
  _COMMUNICATIONCOMMAND_COMMAND._serialized_end=723
  _COMMUNICATIONCOMMAND_RESPONSE._serialized_start=725
  _COMMUNICATIONCOMMAND_RESPONSE._serialized_end=800
# @@protoc_insertion_point(module_scope)
