# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import message_info_pb2 as message__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x10\x61utonomous_proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12message_info.proto\"\xa6\x06\n\x07\x43ontrol\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.autonomous_proto.MessageInfo\x12\x32\n\x04mode\x18\x02 \x01(\x0e\x32$.autonomous_proto.Control.Mode.Value\x12<\n\tdirection\x18\x03 \x03(\x0e\x32).autonomous_proto.Control.Direction.Value\x12\t\n\x01k\x18\x04 \x03(\x01\x12\n\n\x02kv\x18\x05 \x03(\x01\x12\t\n\x01v\x18\x06 \x03(\x01\x12\x0b\n\x03\x61\x63\x63\x18\x07 \x03(\x01\x12\x10\n\x08throttle\x18\x08 \x03(\x01\x12\r\n\x05\x62rake\x18\t \x03(\x01\x12\x34\n\x08priority\x18\n \x01(\x0b\x32\".autonomous_proto.Control.Priority\x1a\x39\n\x04Mode\"1\n\x05Value\x12\x0b\n\x07unknown\x10\x00\x12\x0e\n\nautonomous\x10\x01\x12\x0b\n\x07standby\x10\x02\x1aS\n\tDirection\"F\n\x05Value\x12\x0b\n\x07unknown\x10\x00\x12\x0b\n\x07\x66orward\x10\x01\x12\x15\n\x08\x62\x61\x63kward\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x0c\n\x07neutral\x10\x80\x08\x1a\xe3\x02\n\x08Priority\x12)\n\x04mode\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\tdirection\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12&\n\x01k\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\'\n\x02kv\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12&\n\x01v\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12(\n\x03\x61\x63\x63\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12-\n\x08throttle\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12*\n\x05\x62rake\x18\x08 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"k\n\rControlLimits\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.autonomous_proto.MessageInfo\x12+\n\x05v_max\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROL._serialized_start=88
  _CONTROL._serialized_end=894
  _CONTROL_MODE._serialized_start=394
  _CONTROL_MODE._serialized_end=451
  _CONTROL_MODE_VALUE._serialized_start=402
  _CONTROL_MODE_VALUE._serialized_end=451
  _CONTROL_DIRECTION._serialized_start=453
  _CONTROL_DIRECTION._serialized_end=536
  _CONTROL_DIRECTION_VALUE._serialized_start=466
  _CONTROL_DIRECTION_VALUE._serialized_end=536
  _CONTROL_PRIORITY._serialized_start=539
  _CONTROL_PRIORITY._serialized_end=894
  _CONTROLLIMITS._serialized_start=896
  _CONTROLLIMITS._serialized_end=1003
# @@protoc_insertion_point(module_scope)
