# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: local_path.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import message_info_pb2 as message__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10local_path.proto\x12\x10\x61utonomous_proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12message_info.proto\"\xff\x02\n\tLocalPath\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.autonomous_proto.MessageInfo\x12>\n\tdirection\x18\x02 \x01(\x0e\x32+.autonomous_proto.LocalPath.Direction.Value\x12\x31\n\x06points\x18\x03 \x03(\x0b\x32!.autonomous_proto.LocalPath.Point\x1a\x45\n\tDirection\"8\n\x05Value\x12\x0b\n\x07unknown\x10\x00\x12\x0b\n\x07\x66orward\x10\x01\x12\x15\n\x08\x62\x61\x63kward\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x1a\x88\x01\n\x05Point\x12)\n\x03lat\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12)\n\x03lon\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12)\n\x03\x61lt\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.DoubleValueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'local_path_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCALPATH._serialized_start=91
  _LOCALPATH._serialized_end=474
  _LOCALPATH_DIRECTION._serialized_start=266
  _LOCALPATH_DIRECTION._serialized_end=335
  _LOCALPATH_DIRECTION_VALUE._serialized_start=279
  _LOCALPATH_DIRECTION_VALUE._serialized_end=335
  _LOCALPATH_POINT._serialized_start=338
  _LOCALPATH_POINT._serialized_end=474
# @@protoc_insertion_point(module_scope)
