# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12message_info.proto\x12\x10\x61utonomous_proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xab\x07\n\x0bMessageInfo\x12\x35\n\x07sources\x18\x01 \x03(\x0b\x32$.autonomous_proto.MessageInfo.Source\x12\x43\n\x0bmodule_name\x18\x02 \x01(\x0e\x32..autonomous_proto.MessageInfo.ModuleName.Value\x12\x41\n\ntopic_name\x18\x03 \x01(\x0e\x32-.autonomous_proto.MessageInfo.TopicName.Value\x12*\n\x05\x63ount\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12.\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x1a\xa4\x01\n\nModuleName\"\x95\x01\n\x05Value\x12\x0b\n\x07unknown\x10\x00\x12\x12\n\rmsg_converter\x10\x80\x04\x12\x1c\n\x17\x63ommunication_utilities\x10\x80\x08\x12\x0c\n\x07\x63opycat\x10\xf8U\x12\x12\n\rlocal_roadnet\x10\xe0]\x12\x13\n\x0emotion_control\x10\x80`\x12\x16\n\tundefined\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x1a\xbb\x01\n\tTopicName\"\xad\x01\n\x05Value\x12\x0b\n\x07unknown\x10\x00\x12\x12\n\rvehicle_state\x10\x80\x08\x12\x0f\n\nnavigation\x10\x80\x10\x12\x0f\n\nlocal_path\x10\x80P\x12\x11\n\x0c\x63opycat_path\x10\xf8U\x12\x0c\n\x07\x63ontrol\x10\x80`\x12\x13\n\x0e\x63ontrol_limits\x10\x81`\x12\x13\n\x0e\x63ontrol_sphere\x10\x82`\x12\x16\n\tundefined\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x1a\x9b\x02\n\x06Source\x12\x43\n\x0bmodule_name\x18\x01 \x01(\x0e\x32..autonomous_proto.MessageInfo.ModuleName.Value\x12\x41\n\ntopic_name\x18\x02 \x01(\x0e\x32-.autonomous_proto.MessageInfo.TopicName.Value\x12*\n\x05\x63ount\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12.\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12-\n\x08time_get\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int64Valueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEINFO._serialized_start=73
  _MESSAGEINFO._serialized_end=1012
  _MESSAGEINFO_MODULENAME._serialized_start=372
  _MESSAGEINFO_MODULENAME._serialized_end=536
  _MESSAGEINFO_MODULENAME_VALUE._serialized_start=387
  _MESSAGEINFO_MODULENAME_VALUE._serialized_end=536
  _MESSAGEINFO_TOPICNAME._serialized_start=539
  _MESSAGEINFO_TOPICNAME._serialized_end=726
  _MESSAGEINFO_TOPICNAME_VALUE._serialized_start=553
  _MESSAGEINFO_TOPICNAME_VALUE._serialized_end=726
  _MESSAGEINFO_SOURCE._serialized_start=729
  _MESSAGEINFO_SOURCE._serialized_end=1012
# @@protoc_insertion_point(module_scope)
