# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: navigation_path.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_info_pb2 as message__info__pb2
import navigation_pb2 as navigation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15navigation_path.proto\x12\x10\x61utonomous_proto\x1a\x12message_info.proto\x1a\x10navigation.proto\"x\n\x0eNavigationPath\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.autonomous_proto.MessageInfo\x12\x37\n\x08position\x18\x02 \x03(\x0b\x32%.autonomous_proto.Navigation.Positionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navigation_path_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONPATH._serialized_start=81
  _NAVIGATIONPATH._serialized_end=201
# @@protoc_insertion_point(module_scope)
